# Generated by Django 3.1.1 on 2021-03-01 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acadYear', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=240)),
                ('body', models.CharField(max_length=25000)),
                ('medium', models.CharField(max_length=100)),
                ('acadYear', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('questionBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.student')),
            ],
        ),
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.CharField(max_length=30000)),
                ('answerBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.student')),
                ('whichQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.question')),
            ],
        ),
    ]
