# Generated by Django 3.1.6 on 2021-03-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_student_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='board',
            field=models.CharField(default='SSC', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='board',
            field=models.CharField(default='SSC', max_length=100),
        ),
    ]
